export default {
  GET_HOT_DOGS: {
    FETCH: 'GET_HOT_DOGS_FETCH',
    SUCCESS: 'GET_HOT_DOGS_SUCCESS',
    ERROR: 'GET_HOT_DOGS_ERROR', 
  },
  POST_HOT_DOG: {
    FETCH: 'POST_HOT_DOG_FETCH',
    SUCCESS: 'POST_HOT_DOG_SUCCESS',
    ERROR: 'POST_HOT_DOG_ERROR',
  },
  DELETE_HOT_DOG: {
    FETCH: 'DELETE_HOT_DOG_FETCH',
    SUCCESS: 'DELETE_HOT_DOG_SUCCESS',
    ERROR: 'DELETE_HOT_DOG_ERROR',
  },
  UPDATE_HOT_DOG: {
    FETCH: 'UPDATE_HOT_DOG_FETCH',
    SUCCESS: 'UPDATE_HOT_DOG_SUCCESS',
    ERROR: 'UPDATE_HOT_DOG_ERROR',
  },
  HANDLE_EDIT_FORM: 'HANDLE_EDIT_FORM'
}